services:
  - name: "Service A"
    description: "Description of Service A with additions again"
    environments:
      - name: "Development"
        description: "Development environment for Service A"
      - name: "Test"
        description: "Test environment for Service A"
      - name: "Prod"
        description: "Prod environment for Service A"