name: Generate and Deploy Documentation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'METADATA/**'
      - 'TEMPLATES/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'METADATA/**'
      - 'TEMPLATES/**'


jobs:
  generate-docs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc generate-docs.ts

      - name: Generate Documentation
        run: node generate-docs.js

      # Add steps to commit and push documentation if needed
