name: Generate and Deploy Documentation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'METADATA/**'
      - 'TEMPLATES/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'METADATA/**'
      - 'TEMPLATES/**'


jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc generate-docs.ts

      - name: Generate Documentation
        run: node generate-docs.js

      # Add steps to commit and push documentation if needed
